apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vision
  name: vision
  namespace: adeola-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vision
  strategy: {}
  template:
    metadata:
      labels:
        app: vision
    spec:
      containers:
      - image: IMAGE_NAME
        name: vision
        ports:
        - containerPort: 5000
        resources: {}
status: {}
